// Generated by CoffeeScript 1.6.2
(function() {
  var isLocalUrl, whitelist;

  whitelist = ["http://jsonip.com"];

  isLocalUrl = function(url) {
    var protocol;

    protocol = url.split("://")[0];
    return protocol === 'file' || protocol === 'chrome-extension';
  };

  chrome.webRequest.onBeforeRequest.addListener(function(info) {
    var _this = this;

    return $.get('http://jsonip.com', function(data) {
      var ip, ips;

      ip = data.ip;
      ips = localStorage.getItem('proxy_ips');
      if ((ips != null) && ips.indexOf(window.ip) !== -1) {
        return chrome.browserAction.setIcon({
          path: "assets/icon_on.png"
        });
      } else {
        chrome.browserAction.setIcon({
          path: "assets/icon_off.png"
        });
        if (localStorage.getItem('show_alerts') === 'true') {
          if (isLocalUrl(info.url) || $.inArray(info.url, whitelist) === 0) {
            return {
              cancel: false
            };
          } else {
            return {
              redirectUrl: chrome.extension.getURL('blocked.html')
            };
          }
        }
      }
    });
  }, {
    urls: ["<all_urls>"]
  }, ["blocking"]);

}).call(this);
