// Generated by CoffeeScript 1.6.3
(function() {
  var isLocalUrl, whitelist;

  whitelist = ["http://jsonip.com/"];

  isLocalUrl = function(url) {
    var protocol;
    protocol = url.split("://")[0];
    return protocol === 'file' || protocol === 'chrome-extension';
  };

  chrome.webRequest.onBeforeRequest.addListener(function(info) {
    var ip, ips, showAlerts, urlWhitelisted,
      _this = this;
    $.ajaxSetup({
      async: false
    });
    ip = "";
    $.get('http://jsonip.com').done(function(data) {
      return ip = data.ip;
    });
    ips = localStorage.getItem('proxy_ips');
    if ((ips != null) && ips.indexOf(ip) !== -1) {
      return chrome.browserAction.setIcon({
        path: "assets/icon_on.png"
      });
    } else {
      chrome.browserAction.setIcon({
        path: "assets/icon_off.png"
      });
      urlWhitelisted = isLocalUrl(info.url) || $.inArray(info.url, whitelist) === 0;
      showAlerts = localStorage.getItem('show_alerts') === 'true';
      if (!showAlerts || urlWhitelisted) {
        return {
          cancel: false
        };
      }
    }
    return {
      redirectUrl: chrome.extension.getURL('blocked.html')
    };
  }, {
    urls: ["<all_urls>"]
  }, ["blocking"]);

}).call(this);
