// Generated by CoffeeScript 1.6.3
(function() {
  $.get('http://jsonip.com', function(data) {
    var ips, state;
    $('#address').text(data.ip);
    ips = localStorage.getItem('proxy_ips');
    state = "off";
    if ((ips != null) && localStorage.proxy_ips.indexOf(data.ip) !== -1) {
      state = "on";
    }
    $('#thumbs_image').attr("src", "assets/thumbs_" + state + ".png").attr("alt", "Proxy is " + state + "!");
    return chrome.browserAction.setIcon({
      path: "assets/icon_" + state + ".png"
    });
  });

  $('#running').prop('checked', localStorage.getItem('show_alerts') === 'true');

  $('#running').change(function() {
    return localStorage.setItem('show_alerts', $('#running').is(':checked'));
  });

}).call(this);
